name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: install pm2
      run: npm install -g pm2

    - name: check pm2 
      run: pm2 --version

    - name: Run tests
      run: ./node_modules/.bin/pm2 start run.sh --name backend_pawan_carrental
